/*
 * STEPPER_Program.c
 *
 *  Created on: Oct 28, 2022
 *      Author: User
 */

#include "./STEPPER.h"

void STEP_voidInit()
{
    DIO_InitPin(STEPPER_PORT,BLUE_COIL_PIN,PIN_OUTPUT,PIN_LOW);
    DIO_InitPin(STEPPER_PORT,PINK_COIL_PIN,PIN_OUTPUT,PIN_LOW);
    DIO_InitPin(STEPPER_PORT,YELLOW_COIL_PIN,PIN_OUTPUT,PIN_LOW);
    DIO_InitPin(STEPPER_PORT,ORANGE_COIL_PIN,PIN_OUTPUT,PIN_LOW);

}

void STEP_voidFullStep()
{
    DIO_WritePin(STEPPER_PORT, BLUE_COIL_PIN, PIN_HIGH);
    DIO_WritePin(STEPPER_PORT, PINK_COIL_PIN, PIN_LOW);
    DIO_WritePin(STEPPER_PORT, YELLOW_COIL_PIN, PIN_HIGH);
    DIO_WritePin(STEPPER_PORT, ORANGE_COIL_PIN, PIN_HIGH);
    _delay_ms(10);
    DIO_WritePin(STEPPER_PORT, BLUE_COIL_PIN, PIN_HIGH);
    DIO_WritePin(STEPPER_PORT, PINK_COIL_PIN, PIN_HIGH);
    DIO_WritePin(STEPPER_PORT, YELLOW_COIL_PIN, PIN_LOW);
    DIO_WritePin(STEPPER_PORT, ORANGE_COIL_PIN, PIN_HIGH);
    _delay_ms(10);
    DIO_WritePin(STEPPER_PORT, BLUE_COIL_PIN, PIN_HIGH);
    DIO_WritePin(STEPPER_PORT, PINK_COIL_PIN, PIN_HIGH);
    DIO_WritePin(STEPPER_PORT, YELLOW_COIL_PIN, PIN_HIGH);
    DIO_WritePin(STEPPER_PORT, ORANGE_COIL_PIN, PIN_LOW);
    _delay_ms(10);
    DIO_WritePin(STEPPER_PORT, BLUE_COIL_PIN, PIN_LOW);
    DIO_WritePin(STEPPER_PORT, PINK_COIL_PIN, PIN_HIGH);
    DIO_WritePin(STEPPER_PORT, YELLOW_COIL_PIN, PIN_HIGH);
    DIO_WritePin(STEPPER_PORT, ORANGE_COIL_PIN, PIN_HIGH);
    _delay_ms(10);
}

void STEP_voidMotorAngle(uint32_t A_u32Angle)
{
    uint32_t local_u32Angle = ((NO_OF_STEPS_FOR_360 * A_u32Angle) / CIRCLE_ANGLE);
    uint32_t local_u32Steps = local_u32Angle / NO_OF_COILS;
    for (uint16_t i = 0; i < local_u32Steps; i++)
    {
        DIO_WritePin(STEPPER_PORT, BLUE_COIL_PIN, PIN_HIGH);
        DIO_WritePin(STEPPER_PORT, PINK_COIL_PIN, PIN_LOW);
        DIO_WritePin(STEPPER_PORT, YELLOW_COIL_PIN, PIN_HIGH);
        DIO_WritePin(STEPPER_PORT, ORANGE_COIL_PIN, PIN_HIGH);
        _delay_ms(10);
        DIO_WritePin(STEPPER_PORT, BLUE_COIL_PIN, PIN_HIGH);
        DIO_WritePin(STEPPER_PORT, PINK_COIL_PIN, PIN_HIGH);
        DIO_WritePin(STEPPER_PORT, YELLOW_COIL_PIN, PIN_LOW);
        DIO_WritePin(STEPPER_PORT, ORANGE_COIL_PIN, PIN_HIGH);
        _delay_ms(10);
        DIO_WritePin(STEPPER_PORT, BLUE_COIL_PIN, PIN_HIGH);
        DIO_WritePin(STEPPER_PORT, PINK_COIL_PIN, PIN_HIGH);
        DIO_WritePin(STEPPER_PORT, YELLOW_COIL_PIN, PIN_HIGH);
        DIO_WritePin(STEPPER_PORT, ORANGE_COIL_PIN, PIN_LOW);
        _delay_ms(10);
        DIO_WritePin(STEPPER_PORT, BLUE_COIL_PIN, PIN_LOW);
        DIO_WritePin(STEPPER_PORT, PINK_COIL_PIN, PIN_HIGH);
        DIO_WritePin(STEPPER_PORT, YELLOW_COIL_PIN, PIN_HIGH);
        DIO_WritePin(STEPPER_PORT, ORANGE_COIL_PIN, PIN_HIGH);
        _delay_ms(10);
    }
}